---
# tasks file for roles/fish
- name: install fish shell
  dnf:
    name: fish
    state: latest
  become: yes

- name: deploy config
  copy:
    src: fish
    dest: "{{config_home}}"
    backup: yes
