- name: setup local machine
  hosts: local
  roles:
    - {role: bootstrap, tags: ['bootstrap']}
    - {role: geerlingguy.docker, tags: ['bootstrap'], become: yes}
    - {role: git, tags: ['git']}
    - {role: zsh, tags: ['zsh']}
    - {role: emacs, tags: ['emacs']}
    - {role: qtile, tags: ['qtile']}
    - {role: ssh, tags: ['ssh']}  # This role is configured to use ansible-vault to encrypt ssh keys, disable it by removing from the list
