- name: setup local machine
  hosts: local
  vars:
    config_home: "{{ansible_user_dir}}/.config"
  roles:
     - {role: repositories, tags: ['repos']}
     - {role: bootstrap, tags: ['bs']}
     - {role: i3wm, tags:['wm', 'i3']}
     - {role: alacritty, tags: ['termial', 'alacritty']}
     - {role: fish, tags: ['fish']}
     - {role: powershell, tags: ['pwsh']}
     - {role: asdf-vm, tags: ['asdf']}
