- name: gather all zsh files
  command: ls "{{dotfiles_home}}/roles/zsh/files/zsh.link"
  register: find_result

- name: Check if zshrc exists
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Make sure gitconfig is up to date
  template:
    src: "zshrc.j2"
    dest: "{{dotfiles_user_home}}/.zshrc"


- name: Link zsh folder
  file:
    src: "{{dotfiles_home}}/roles/zsh/files/zsh.link"
    dest: "{{dotfiles_user_home}}/.zsh"
    state: link
    force: yes

- name: Link zshenv file
  file:
    src: "{{dotfiles_home}}/roles/zsh/files/zshenv.link"
    dest: "{{dotfiles_user_home}}/.zshenv"
    state: link
    force: yes
