---
# tasks file for roles/brew
#
- name: installing dependencies
  dnf:
    name:
      - '@Development tools'
      - libxcrypt-compat
  become: yes

- name: install brew
  shell:
    cmd: "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)\""
    creates: "{{ansible_user_dir}}/.linuxbrew"
