---
# tasks file for roles/repositories
- name: Setting up rpm fusion free
  dnf:
    name: 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_version}}.noarch.rpm'
    state: present
  become: yes

- name: Setting up rpm fusion non-free
  dnf:
    name: 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_version}}.noarch.rpm'
    state: present
  become: yes
