---
# tasks file for binfiles
- name: Gather bin files
  find:
    paths: "/home/gergelyorosz/dotfiles/roles/binfiles/files/"
    follow: true
  register: bin_files

- name: Check if .local/bin exists
  stat: path="{{dotfiles_user_home}}/.local/bin"
  register: local_bin_stat

- name: Create .local/bin if not exists
  file:
    dest: "{{dotfiles_user_home}}/.local/bin"
    state: directory
  when: local_bin_stat.stat.exists == false

- name: Link bin files
  file:
    src: "{{item.path}}"
    dest: "{{dotfiles_user_home}}/.local/bin/{{item.path | basename}}"
    state: link
    force: true
  with_items: "{{ bin_files.files }}"
