---
# tasks file for roles/emacs
#
- name: install dependencies
  dnf:
    name:
      - cmake
      - libtool
      - libvterm-devel
      - libvterm-tools
      - ripgrep
      - fd-find
    state: latest
  become: yes

- name: Install emacs
  dnf:
    name: emacs
    state: latest
  become: yes

- name: Getting doom emacs
  git:
    repo: 'https://github.com/hlissner/doom-emacs'
    dest: '{{ansible_user_dir}}/.emacs.d'
    version: 'develop'

- name: Deploy personal config
  copy:
    src: .doom.d
    dest: "{{ansible_user_dir}}"
    backup: yes

- name: Bootstraping emacs
  expect:
    command: bin/doom install
    responses:
      (?i)Download and install all-the-icon's fonts: y
    timeout: 600
  args:
    chdir: '/home/gergelyorosz/.emacs.d'
