---
# tasks file for roles/powershell
#
- name: Import key
  rpm_key:
    key: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  become: yes

- name: setup microsoft repository
  get_url:
    url: "https://packages.microsoft.com/config/rhel/7/prod.repo"
    dest: "/etc/yum.repos.d/microsoft.repo"
  become: yes

- name: install powershell
  dnf:
    name: powershell
    state: latest
  become: yes
