---
# tasks file for roles/rofi
#
- name: Install rofi
  dnf:
    name: rofi
    state: latest
  become: yes

- name: create config dir
  file:
    name: "{{config_home}}/rofi"
    state: directory

- name: deploy config
  copy:
    src: rofi
    dest: "{{config_home}}"
    backup: yes
