complete -c broot -n "__fish_use_subcommand" -l outcmd -d 'where to write the produced cmd (if any)'
complete -c broot -n "__fish_use_subcommand" -s c -l cmd -d 'commands to execute (space separated, experimental)'
complete -c broot -n "__fish_use_subcommand" -s o -l out -d 'where to write the produced path (if any)'
complete -c broot -n "__fish_use_subcommand" -s g -l gitignore -d 'respect .gitignore rules (yes, no, auto)'
complete -c broot -n "__fish_use_subcommand" -l height -d 'height (if you don\'t want to fill the screen or for file export)'
complete -c broot -n "__fish_use_subcommand" -l print-shell-function -d 'print to stdout the br function for a given shell'
complete -c broot -n "__fish_use_subcommand" -s d -l dates -d 'show the last modified date of files and directories'
complete -c broot -n "__fish_use_subcommand" -s h -l hidden -d 'show hidden files'
complete -c broot -n "__fish_use_subcommand" -l install -d 'install or reinstall the br shell function'
complete -c broot -n "__fish_use_subcommand" -l no-style -d 'whether to remove all style and colors'
complete -c broot -n "__fish_use_subcommand" -s f -l only-folders -d 'only show folders'
complete -c broot -n "__fish_use_subcommand" -s p -l permissions -d 'show permissions, with owner and group'
complete -c broot -n "__fish_use_subcommand" -s s -l sizes -d 'show the size of files and directories'
complete -c broot -n "__fish_use_subcommand" -l help -d 'Prints help information'
complete -c broot -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
